### ISSUE TITLE
Question. Trying to attach in a dynamic way, but it does not work

### ISSUE THREAD

**Issue by Vovan2006** [opentracing-contrib/java-specialagent#103]
Hello guys,
I am trying to attach to my app which works in a docker container, but it does not work for me.
I use a recent version(1.3.1) of a special agent. Here is a command which I enter in cmd:
java -Xbootclasspath/a:$JAVA_HOME/lib/tools.jar -Dsa.tracer=jaeger -Dsa.log.level=FINEST -DJAEGER_AGENT_HOST=http://127.0.0.1 -DJAEGER_AGENT_PORT=5775 -DJAEGER_REPORTER_LOG_SPANS=true -DJAEGER_SAMPLER_TYPE=const -DJAEGER_SAMPLER_PARAM=1 -DJAEGER_SERVICE_NAME=my-app -jar trace/opentracing-specialagent-1.3.1.jar PID

In the container I use the java-1.8.0-amazon-corretto.
Jaeger is started in All-in-one mode:
docker run -d -p 5775:5775/udp -p 16686:16686 jaegertracing/all-in-one:latest

As a result I can see a following information in a log file:
Jun 25, 2019 7:52:37 AM io.opentracing.contrib.specialagent.RuleClassLoader isCompatible
WARNING: Disallowing instrumentation with "spring-messaging" due to "fingerprint.bin mismatch" errors:
 MISSING org.springframework.integration.channel.AbstractMessageChannel,
 MISSING org.springframework.integration.channel.interceptor.GlobalChannelInterceptorWrapper,
 MISSING org.springframework.integration.context.IntegrationObjectSupport,
 MISSING org.springframework.integration.support.MutableMessageHeaders in: file:/tmp/opentracing-specialagent3803143141083749044/META-INF/opentracing-specialagent/specialagent-spring-messaging-1.3.1.jar

Then I process several requests to my app, which I think might be added to Jaeger storage, but unfortunately they were not added.  So could you help me with my issue ? Maybe I am wrong with some steps which I mentioned before.

**Comment by SevaSafris** [comment]
Hi @Vovan2006, I hope I can help you move forward with SpecialAgent.

The command you provide seems like you're using the dynamic attach method of attaching to a target java process, but it's missing the `PID` at the end. Did you omit this intentionally? Regardless, given the fact that you see log output from SpecialAgent, I believe you're attaching to the target process correctly.

For which specific libraries are you expecting to see traces? I'm assuming you have a Spring, or Spring Boot application, given the log output you provided. SpecialAgent supports the latest major version of Spring, but it would be good to know from which Spring services you're expecting to see traces.

The log you've posted is output from the fingerprinting mechanism. This mechanism prevents instrumentation plugins from inadvertently loading in environments where the plugin is not compatible. The way it works is:
1. SpecialAgent's build process fingerprints the 3rd-party library for each instrumentation plugin, since each instrumentation plugin is implemented for a particular version of a 3rd-party library. The fingerprint is present for each plugin inside the SpecialAgent's JAR.
1. When you attach SpecialAgent to a target runtime, it installs triggers for each plugin. If a trigger is invoked, the fingerprinting mechanism attempts to match the fingerprint (that is packaged inside the SpecialAgent) of the 3rd-party library (for which the plugin is implemented) to the fingerprint that is generated the target runtime's class loader from which the trigger is invoked.
1. If the fingerprints match, the plugin is enabled. If it does not match, the plugin is disabled, and the log tells you why it was disabled. In your case, the reason is that several classes are missing in your app's runtime. These classes must be present for the `spring-messaging` plugin to work, and therefore, since they're not present, it must mean that you do not in fact have Spring Messaging in your runtime. **Please correct me if I'm wrong.**

I see that you specify `-Dsa.log.level=FINEST`. With this log spec, you should find messages that start with: `Allowing instrumentation with ...`. These lines will tell you which instrumentation plugins are loaded successfully. As a side-note, `FINEST` logging level is excessively verbose. The `FINER` log level excludes detail class and resource loading logs, and will reduce 90% of the log verbosity. To save yourself a headache analyzing logs, see if `FINER` is enough for you.

**Comment by Vovan2006** [comment]
Hi @SevaSafris, 
thanks for so fast response !
You are absolutely right I have been using the dynamic attach method of attaching to a target java process.
Regarding the PID I have already fixed my previous comment and added it to the end of the command.
But my main question was why traces do not appear in a storage(Jaeger) and moreover I could not figure it out  because I could not get any logs despite the fact I set up - -Dsa.log.level=FINEST

**Comment by SevaSafris** [comment]
Ah, yes, that's right. We currently have an outstanding issue for dynamic attach concerning propagation of system arguments from the agent process to the target process. This is currently at the top of my list of priorities, and I expect it to be resolved no later than tomorrow. Apologies for the wait time. I'll respond on this issue once that bug is resolved.

**Comment by SevaSafris** [comment]
Hi @Vovan2006, I have resolved the issue with propagation of system arguments for invocation via dynamic attach. The fix will allow you to pass arguments from the agent command line to the target application. This has been pushed and released to the current development version: 1.3.2-SNAPSHOT. For download instructions, please refer to [this guide](https://github.com/opentracing-contrib/java-specialagent/#2112-development).

Once you run with the development version, you can pass the `-Dsa.log.level=FINER` argument to see what instrumentation plugins are being loaded. Then, you can check if these coincide with the 3rd-party libraries from which you expect to see traces.

**Comment by Vovan2006** [comment]
@SevaSafris, 
Thanks for your answer. 
I will take a new version, check my case again and let you know a result

**Comment by Vovan2006** [comment]
@SevaSafris, 
I have checked the new version and know I see all logging regarding level which was set up in a system property, thereby I see that Jaeger tracer is chosen. And I am very happy about it ))
But unfortunately spans still do not appear in Jaeger storage. How else I can check my environment ?
Here is my commands which I enter:
1. docker run -d -p 5775:5775/udp -p 16686:16686 jaegertracing/all-in-one:latest
2. java -Xbootclasspath/a:$JAVA_HOME/lib/tools.jar -Dsa.tracer=jaeger -Dsa.log.level=FINE -Dsa.instrumentation.plugin.spring-messaging.enable=false -DJAEGER_AGENT_HOST=http://127.0.0.1 -DJAEGER_AGENT_PORT=5775 -DJAEGER_REPORTER_LOG_SPANS=true -DJAEGER_SAMPLER_TYPE=const -DJAEGER_SAMPLER_PARAM=1 -DJAEGER_SERVICE_NAME=app -jar trace/opentracing-specialagent-1.3.2-SNAPSHOT.jar PID

Also, before it you asked me about "specific libraries" which I use. What did you mean by  "specific libraries" ?

**Comment by SevaSafris** [comment]
Hi @Vovan2006, I'm glad to hear you're now able to see log statements from SpecialAgent in your target process.

The SpecialAgent is an engine that automatically installs a specific set of Instrumentation Plugins into a target runtime. The Instrumentation Plugins are specific, and are listed [here](https://github.com/opentracing-contrib/java-specialagent/#61-instrumentation-plugins).

With regard to "specific libraries", the question is regarding what you're expecting to see traced. From the link I just provided, you get a general sense of what Instrumentation Plugins SpecialAgent supports. And so, does your application use libraries that overlap with this list? If yes, then you should see traces. If no, then the libraries you're expecting to see traces from are simply not instrumented.

**Comment by Vovan2006** [comment]
@SevaSafris, 
should I add needed dependencies of  Instrumentation Plugins to my app ? Or it is responsibility of SpecialAgent and  target process only should use libraries which overlap with list of The Instrumentation Plugins ?

**Comment by SevaSafris** [comment]
@Vovan2006, you do not need to add any dependencies or anything extra. The question remains: "What traces are you expecting to see? i.e., for which libraries?".

**Comment by Vovan2006** [comment]
@SevaSafris,
I would like to see at least traces for these  libraries:
Spring boot(rest controller),
org.springframework.web.client.AsyncRestTemplate,
org.springframework.web.client.RestTemplate.
Is it possible ?

**Comment by Vovan2006** [comment]
@SevaSafris,
As I understood if a log shows a following record  

> Allowing instrumentation with "spring-web" due to "fingerprint.bin match" for....

  it means that the SpecilaAgent detected overlapped libraries in my App and  should trace them.
Is that right ?

**Comment by SevaSafris** [comment]
Hi @Vovan2006, apologies for the delayed response. Here are the answers to your questions:
1. `org.springframework.web.client.AsyncRestTemplate` and `org.springframework.web.client.RestTemplate` are instrumented in the **Spring Web Plugin**. The method that is instrumented for both of these classes is: `doExecute`.
2. Yes, "Allowing instrumentation" means that the plugin was triggered, and passed the compatibility test.

If you set `-Dsa.log.level=FINER`, you will see logs of intercepts. The logs look like this:

`-------> Intercept from: ...`

With FINER logging, you can run your app and look for these logs to assert that `doExecute` is being triggered.

Please download the latest version of 1.3.2-SNAPSHOT, since prior builds don't have the logs of intercepts enabled for Spring Web Plugin.

**Comment by Vovan2006** [comment]
@SevaSafris, 
I got a last version which you offered me before and now I have extra questions related to an error which I see in logs:
```
Caused by: java.lang.IllegalAccessError: tried to access class io.opentracing.noop.NoopSpanContextImpl from class io.opentracing.noop.NoopSpanImpl
	at io.opentracing.noop.NoopSpanImpl.context(NoopSpan.java:29)
	at io.opentracing.contrib.specialagent.spring.web.copied.TracingRestTemplateInterceptor.intercept(TracingRestTemplateInterceptor.java:78)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:92)
```
As I understood, the "org.springframework.http.client.InterceptingClientHttpRequest" accounts for this error. There are not rules/plugins for this library in the SpecialAgent. Correct me please if I am wrong

**Comment by SevaSafris** [comment]
Hi @Vovan2006, the error you are seeing is due to the following situation:

1. Though `InterceptingClientHttpRequest` is not explicitly instrumented, its `execute` method invokes a `ClientHttpRequestInterceptor` that _is_ instrumented by SpecialAgent.
2. When invoked, `GlobalTracer.get()` returns a `NoopTracer`, which is _not right._ **Question for you: Can you provide the full log, so I can see when/where in the log the exception occurs?**
3. The instrumented interceptor then attempts to create a `NoopSpan`, which attempts to access `NoopSpanContextImpl.INSTANCE`, and this throws the `IllegalAccessException`.
4. Looking at the code, it _should not throw the exception,_ because `NoopSpanContextImpl.INSTANCE` has package-private accessibility. However, the exception occurs because it seems that `NoopSpanContextImpl` and `NoopSpan` are loaded in different class loaders. This leads to another **question for you: Are you including OpenTracing APIs and/or the `opentracing-noop` dependency in your runtime?** I am not clear on how `NoopSpanContextImpl` and `NoopSpan` can be loaded in different class loaders.

I suspect this is a bug in the way SpecialAgent auto-installs the Spring Web Instrumentation Plugin.

**Comment by Vovan2006** [comment]
@SevaSafris,
here is the full log which you asked me to provide:

> org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IllegalAccessError: tried to access class io.opentracing.noop.NoopSpanContextImpl from class io.opentracing.noop.NoopSpanImpl
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1053)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
> 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.mycompany.server.common.config.SomeRequestFilter.doFilterInternal(SomeRequestFilter.java:333)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
> 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
> 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
> 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
> 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at com.mycompany.server.core.filters.AnotherFilter.doFilter(AnotherFilter.java:555)
> 	at com.mycompany.server.core.filters.SomeFilter.doFilter(SomeFilter.java:888)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at com.mycompany.server.core.filters.SomeFilter.doFilter(SomeFilter.java:222)
> 	at com.mycompany.server.core.filters.SomeSpecialFilter.doFilter(SomeSpecialFilter.java:333)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:157)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalAccessError: tried to access class io.opentracing.noop.NoopSpanContextImpl from class io.opentracing.noop.NoopSpanImpl
> 	at io.opentracing.noop.NoopSpanImpl.context(NoopSpan.java:29)
> 	at io.opentracing.contrib.specialagent.spring.web.copied.TracingRestTemplateInterceptor.intercept(TracingRestTemplateInterceptor.java:78)
> 	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:92)
> 	at com.mycompany.server.common.config.SomeInterceptor.intercept(SomeInterceptor.java:111)
> 	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:92)
> 	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:76)
> 	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
> 	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
> 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
> 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
> 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579)
> 	at com.mycompany.server.core.service.SomeClient.getSomeInfo(SomeClient.java:777)
> 	at com.mycompany.server.core.web.rest.SomeResource.getSomeInfo(SomeResource.java:666)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
> 	... 106 common frames omitted

Regarding your second question about **including OpenTracing APIs and/or the opentracing-noop dependency in your runtime** I have only this dependency - io.opentracing.contrib:opentracing-spring-cloud-core. I need it because I have a custom trace implementation which works depending on app properties.

**Comment by SevaSafris** [comment]
@Vovan2006, could you provide more of the log for me? I need to know _when_ this exception is thrown -- i.e. what log messages happened before this exception is encountered.

**Comment by SevaSafris** [comment]
Hi @Vovan2006, do you have an update regarding this issue? Are you still experiencing problems with dynamic attach?

**Comment by Vovan2006** [comment]
Hi @SevaSafris, I have decided to play with static  attach for now. So this issue can be closed
