### ISSUE TITLE
Trying to attach in a static way, but it does not work

### ISSUE THREAD

**Issue by Vovan2006** [opentracing-contrib/java-specialagent#105]
![error](https://user-images.githubusercontent.com/16269410/60513112-e66e7600-9cc5-11e9-9876-746457b623ca.JPG)
Hello Java-special-agent team,
I am trying to attach to my app in a static way and do it from my intelij idea, but unfortunately I can't do it because of an error which appears strait away after starting app:

> java.lang.ExceptionInInitializerError
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
> 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
> Caused by: java.lang.IllegalStateException: Name of -javaagent JAR, which is currently file:pathToJar\opentracing-specialagent-1.3.2-SNAPSHOT.jar, must be: opentracing-specialagent-1.3.2-SNAPSHOT.jar
> 	at io.opentracing.contrib.specialagent.SpecialAgentUtil.assertJavaAgentJarName(SpecialAgentUtil.java:179)
> 	at io.opentracing.contrib.specialagent.SpecialAgent.<clinit>(SpecialAgent.java:105)
> 	... 6 more

I use windows 10 as OS.
The error is thrown from SpecialAgentUtil.assertJavaAgentJarName() method. Line #179:

>         else {
>           final String jarName = getName(location.toString());
>           if (!jarName.equals(bootClassPathManifestEntry))
>             throw new IllegalStateException("Name of -javaagent JAR, which is currently " + jarName + ", must be: " + bootClassPathManifestEntry);
>         }

**Comment by SevaSafris** [comment]
Please remove the quotes around the argument and try again.

**Comment by Vovan2006** [comment]
@SevaSafris, the same result

**Comment by Vovan2006** [comment]
@SevaSafris,
it seems the problem is hidden in SpecialAgentUtil.getName method.
It would be better to use **File.separatorChar** instead '47' and **File.separator** instead '/'

**Comment by SevaSafris** [comment]
@Vovan2006, you're absolutely right. Thank you for finding this. I've just corrected this bug and have pushed to master. Hopefully, [Travis](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/553747212) will build and deploy this ASAP.

**Comment by Vovan2006** [comment]
Thanks @SevaSafris,
I am closing this issue
