### ISSUE TITLE
NPE during processing io.opentracing.contrib.jdbc.JdbcTracingUtils.buildSpan

### ISSUE THREAD

**Issue by Vovan2006** [opentracing-contrib/java-specialagent#110]
Hi everyone,
I use a static way to attach to my app. During starting the app NPE is thrown.  A detailed error log can be found In an attached file. As I understood it is in some way related to the liquibase which I use in my app
[npe.log](https://github.com/opentracing-contrib/java-specialagent/files/3359300/npe.log)

**Comment by SevaSafris** [comment]
Hi @Vovan2006, the stacktrace of the exception does not mention classes that belong to the SpecialAgent. It looks like this is an issue specific to the [JDBC Instrumentation Plugin](https://github.com/opentracing-contrib/java-jdbc).

**Comment by malafeev** [comment]
I believe it's fixed in `0.1.5` release, SA requires update

**Comment by SevaSafris** [comment]
Thanks for the comment @malafeev. I have upgraded the JDBC Instrumentation Plugin to 0.1.5. Once [this build is finished](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/554324949), it will be available on Maven Central Snapshots.
