### ISSUE TITLE
Add Wavefront Tracer Plugin

### ISSUE THREAD

**Issue by hanwavefront** [opentracing-contrib/java-specialagent#167]
Just a heads up -- We are working on a [Wavefront OpenTracing Bundle](https://github.com/wavefrontHQ/wavefront-opentracing-bundle-java) that serves as a tracer plugin, and we would like to add it as an internal tracer plugin to the SpecialAgent.  We plan to open a PR to do so once the bundle is released.  Please let me know if there's anything you would like to discuss.  Thanks.

**Comment by SevaSafris** [comment]
Hi @hanwavefront, sounds good. I briefly looked through your code. If you need any help, please let me know.
