### ISSUE TITLE
question. How does this work with springfranework?

### ISSUE THREAD

**Issue by etsangsplk** [opentracing-contrib/java-specialagent#17]
can you give examples? i am particularly insterested in how it can automatically trace request processd by conteollers

**Comment by SevaSafris** [comment]
Hi @etsangsplk, the SpecialAgent does not currently support any springframework instrumentation modules. For a list of currently supported modules, please look [here](https://github.com/opentracing-contrib/java-specialagent/#supported-instrumentation-plugins).
