### ISSUE TITLE
servlet rule plugin causes extra retries in 403 downstream calls

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#178]
I have come across a very strange problem and thought I'd share in case you have any insights. 

We have a web application that calls other backend/downstream services. This is the same web application as reported in issue #153.  

We ran into an issue where the number of downstream calls to other services resulting in 403 HTTP responses (using Apache HttpClient) increased dramatically (~10x) when the caller (a Jetty/Servlet runtime) had the 'web-servlet-filter' rule enabled. When we removed the agent completely or only disabled the 'servlet' (or web-servlet-filter) rule plugin, then the higher number of downstream 403 results did not occur. We confirmed this multiple times using log-scraping of the downstream services.

I updated the servlet rule code to the latest from master today (web-servlet-filter plugin renamed to just servlet, and async support added). The effect is considerably less, but is still about 2x the number of downstream calls. This confirms that it is this plugin. The incoming load does not change (confirmed by JMeter results).

It is concerning, to say the least, that instrumentation here is modifying the behavior of the system in a fundamental way (as opposed to just causing slightly slower response times). Any ideas?

**Comment by SevaSafris** [comment]
Hi @randallt, could you provide me the FINER level log spanning the time you experience 2x the number of calls?

**Comment by randallt** [comment]
Attached. In this case, one downstream service with result code 403 was called 84 times, compared to 34 times with the agent not running.

[sa.log.gz](https://github.com/opentracing-contrib/java-specialagent/files/3717606/sa.log.gz)

**Comment by SevaSafris** [comment]
Hi @randallt, I believe I have found the cause of these duplicated calls. If you could, please grab the [latest snapshot build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) once [this job](https://travis-ci.org/opentracing-contrib/java-specialagent/jobs/597634042) completes, and let me know your findings.

**Comment by randallt** [comment]
Hi @SevaSafris, I pulled the code change in the servlet rule plugin in and it appears to have fixed this issue. Thanks for addressing it in such a speedy manner!

**Comment by SevaSafris** [comment]
Hi @randallt, that's great to hear! Sorry for the bug. The servlet plugin is unfortunately complex, since it has to support Servlet API 2.3, 2.5, and 3+.
