### ISSUE TITLE
Config file to disable rules does not work

### ISSUE THREAD

**Issue by dearboll** [opentracing-contrib/java-specialagent#179]
I am following the [guide](https://github.com/opentracing-contrib/java-specialagent#342-disabling-one-instrumentation-plugin) and I wanna disable some rules such like `servlet` . My start script is like blow. 
``` 
java -javaagent:opentracing-specialagent-1.4.1.jar \
	-Dsa.tracer=jaeger \
       	-Dsa.config=jaeger.config \
	-DJAEGER_SERVICE_NAME=demo-test \
	-Dsa.log.level=FINER \
	-jar demotrace-0.0.1.jar
````
But unfortunately it seems not work, The file jaeger.config is like blow.
```
sa.instrumentation.plugin.spring:web:*.disable=true
```
I wonder if there is a demo config file as example to enable or disable plugins or rules. Thank you a lot ^_^.

**Comment by SevaSafris** [comment]
Hi @dearboll, thank you for opening this issue. This was in fact a bug introduced by the recent changes to the plugin naming convention.

**Comment by SevaSafris** [comment]
Hi @dearboll, this has been fixed. Once [this job](https://travis-ci.org/opentracing-contrib/java-specialagent/jobs/598578470) is done, please [download the latest snapshot](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and try again.
