### ISSUE TITLE
about tracing private method of business logic

### ISSUE THREAD

**Issue by hotdust** [opentracing-contrib/java-specialagent#199]
Because the business team wants to trace private method args to find reason of bug, I think maybe specialagent can help.

I read README.md of Non-Goals:
>The SpecialAgent is not designed to modify application code, beyond the installation of Instrumentation Plugins. For example, there is no facility for dynamically tracing arbitrary code.

Is that means specialagent can not instrument private method?

**Comment by SevaSafris** [comment]
Hi @hotdust, the SpecialAgent is not designed to instrument arbitrary methods. If you would like to instrument some specific methods in your application, you can do this by implementing an [Instrumentation Rule](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api). You can implement your own Instrumentation Rule, and then include this rule to be loaded by SpecialAgent with the `-Dsa.instrumentation.plugin.include=<PLUGIN_JARS>`, where `<PLUGIN_JARS>` is a pathSeparator-delimited (`:` for *NIX, `;` for windows) string of JARs with custom Instrumentation Rules. The Instrumentation Rule API relies on ByteBuddy to perform the bytecode re/transformation. ByteBuddy allows instrumentation of private methods.

**Comment by hotdust** [comment]
@SevaSafris thanks for reply, I will try it. please do not close this issue temporarily.

**Comment by hotdust** [comment]
@SevaSafris I understood specialagent mechanism. I wrote a bytebuddy agent which can intercept all method and get args. (not convert bytebuddy agent code to special agent rule yet)

I have two questions：

1. After adding specialagent, project outputs following logs. How come logs are outputted ?
(the logs are not outputted, if do not use specialagent.)
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
command:
>  java -javaagent:opentracing-specialagent-1.5.0.jar -Dsa.spring -Dsa.tracer=jaeger -DJAEGER_SERVICE_NAME=webproject -DJAEGER_SAMPLER_PARAM=1 -jar target/web-project-1.0-SNAPSHOT.jar


2, skywalking provides @Trace annotation to trace method. Is there any schedule to provide function like that (to trace centain method or all methods of class)?

**Comment by SevaSafris** [comment]
Hi @hotdust, I don't understand your first question.

Regarding your second question: There is no existing mechanism to provide this functionality. If you'd like, you can write an Instrumentation Plugin that implements this functionality.
