### ISSUE TITLE
Logging does not work when using SpecialAgent with dynamic attach

### ISSUE THREAD

**Issue by alvinhom** [opentracing-contrib/java-specialagent#207]
I am trying to use dynamic attach with SpecialAgent to attach to existing Java process.  I am not able to see any logging statements when using Dynamic Attach.  If I use the static approach, then logs are generated.

After looking at the code, looks like the Logger class is instantiated and initialized once before the properties (from SpecialAgent.premain) get set.  So, even though system properties are loaded, the logger instance is not refreshed and thus no logs.  If I add statement to reset the logger after loadProperties, then I can see the logs being generated.

**Comment by SevaSafris** [comment]
Hi @alvinhom, thank you for bringing this bug to our attention. This has been fixed in the current SNAPSHOT build.
