### ISSUE TITLE
We want to use the special agent in the production environment. Is the stability stable now?

### ISSUE THREAD

**Issue by code98** [opentracing-contrib/java-specialagent#220]
We want to use the special agent in the production environment. Is the stability stable now?

About 1 million requests per day.

**Comment by SevaSafris** [comment]
Hi @code98, for a list of supported instrumentation plugins, please refer to [this table](https://github.com/opentracing-contrib/java-specialagent/#61-instrumentation-plugins).  The specified versions of 3rd-party libraries of each plugin is tested [here](https://travis-ci.org/opentracing-contrib/java-specialagent/). As far as "stability" is concerned, the [`AgentRunner` tests](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#5-agentrunner-usage) for each [`AgentRule`](https://github.com/opentracing-contrib/java-specialagent/tree/master/rule), as well as the [regular application tests](https://github.com/opentracing-contrib/java-specialagent/tree/master/test) provide the full scope of testing as is systematically performed for the SpecialAgent.

**Comment by code98** [comment]
Ok, then we will test this program in a small scope. After that, the average daily request will reach 100 million.
