### ISSUE TITLE
Release SpecialAgent v1.5.1

### ISSUE THREAD

**Issue by SevaSafris** [opentracing-contrib/java-specialagent#223]
The v1.5.1 release includes the following updates:

* New [instrumentation plugins](https://github.com/opentracing-contrib/java-specialagent/#supported-instrumentation-plugins): Akka Http Server, OkHttp 4, Play Framework (server and client).
* Include external instrumentation plugins (those which are not included in the SpecialAgent, such as proprietary plugins).
* Fix to `ClassLoaderAgentRule` bug leading to `NoClassDefFoundException`.
* Static Deferred Attach for Spring Boot versions 1.0.0.RELEASE to LATEST.
* Automatic activation of Static Deferred Attach for Spring Boot applications.

**Comment by code98** [comment]
Hello, what features have been updated?

**Comment by SevaSafris** [comment]
Hi @code98, I have updated the description.
