### ISSUE TITLE
After the agent is successfully started, can the special agent dynamically add AgentBuilder?

### ISSUE THREAD

**Issue by code98** [opentracing-contrib/java-specialagent#246]
I want to develop a plugin for a special agent.

For example: I want to intercept an A method. When the A method exits, use Bytebuddy's AgentBuilder to intercept another B method.

![image](https://user-images.githubusercontent.com/10418235/69205100-f1964580-0b83-11ea-83cc-ae09ab480514.png)

Is this scheme feasible?

**Comment by SevaSafris** [comment]
Hi @code98, the SpecialAgent API for plugins/rules allows the full scope of functionality offered by ButeBuddy. I believe what you are asking for is: "Can I do this with ByteBuddy?" If the answer to your question is "yes", then you can do this for a SpecialAgent plugin/rule. Please refer to the [ByteBuddy docs](https://bytebuddy.net/) for help with ByteBuddy.

**Comment by code98** [comment]
Thank you very much for your help
