### ISSUE TITLE
Request for support of Apache Pulsar Functions

### ISSUE THREAD

**Issue by devinbost** [opentracing-contrib/java-specialagent#259]
As per the comment here: 
https://medium.com/opentracing/automatic-tracing-with-java-specialagent-ac1874f9e8e8
that states:

> Is there a 3rd-party library you’d like to see instrumented and integrated with SpecialAgent?
> Please let us know by filing an issue in the SpecialAgent’s GitHub project.

we'd like to see Apache Pulsar Functions instrumented and integrated with SpecialAgent. 
Apache Skywalking already offers support for Pulsar Consumers/Producers, so we don't need instrumentation for Pulsar Consumers/Producers, but we do need instrumentation for Pulsar Functions specifically.

**Comment by SevaSafris** [comment]
Hi @devinbost, thank you for your message. I have presented your request to my team, and neither one of us is familiar with Apache Pulsar. You're the first person to request this 3rd-party library, so it is unfortunately not high on our list of priorities.

If you would like support for this 3rd-party library added to SpecialAgent, you are welcome to implement an Instrumentation Plugin yourself. The scope of this plugins must be: "to instrument Apache Pulsar Functions with OpenTracing API". An example of such a plugin is: [OkHttp](https://github.com/opentracing-contrib/java-okhttp). As you can see, this plugin does not (and must not) know about SpecialAgent. It is simply intended for a single purpose: to instrument OkHttp with OpenTracing API. Once you implement such a plugin for Apache Pulsar Functions, this plugin will be adopted by the the [opentracing-contrib](https://github.com/opentracing-contrib) group (probably named "java-apache-pulsar-functions", or something similar). After this is done, I will write the [Instrumentation Rule](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#4-usage) to integrate your "Apache Pulsar Functions Plugin" in the SpecialAgent.

**Comment by safris** [comment]
@malafeev, can you scope out the best approach for instrumenting Apache Pulsar Functions?

**Comment by malafeev** [comment]
added #322 to have complete support for Apache Pulsar

**Comment by malafeev** [comment]
@devinbost how do you call Pulsar Functions?
From my understanding functions are deployed to cluster and then triggered via command line.
So you would like to have instrumentation of execution of functions in the cluster?
Pulsar Consumers/Producers is client side instrumentation, but Pulsar Functions is server side.

**Comment by devinbost** [comment]
Pulsar functions are triggered by data coming into a topic that the
function is subscribed to.

**Comment by malafeev** [comment]
thanks @devinbost 
so you will run Pulsar cluster with SpecialAgent jar and expect to see traces from Pulsar Functions?
did you try to do that?

**Comment by malafeev** [comment]
done

@devinbost 
When I run broker with special agent I disabled all plugins except pulsar:
```
-Dsa.instrumentation.plugin.*.disable
-Dsa.instrumentation.plugin.pulsar:*.enable
```

And I see trace from client to function (client app also runs with special agent).
