### ISSUE TITLE
I want to develop a monitoring plugin for methods

### ISSUE THREAD

**Issue by code98** [opentracing-contrib/java-specialagent#287]
Configure the method signature in the environment variable and inject trace information into the specified method.
E.g:
-Dsa.config.instrumentation.plugin.method = com.demo.HomeController#homePage; com.demo.HomeController#db

Use ";" to split multiple classes,
Use "#" to split multiple classes and methods,

Then add trace information before and after these methods are executed.

The code has been developed. Can it be merged into the main branch?
Is there anything I need to pay extra attention to?

**Comment by safris** [comment]
Hi @code98, thank you for your work on this plugin. If your code is ready, I can look at it and consider it for inclusion as an internal plugin in the SpecialAgent. Do you have a repo for me to clone?

**Comment by code98** [comment]
OK, I am ready to submit the code. Thank you

**Comment by safris** [comment]
Hi @code98, FYI: SpecialAgent v1.5.4 will be released in 1 week. I am awaiting your changes on #293.

**Comment by safris** [comment]
This has been superseded by #375.
