### ISSUE TITLE
Add support for global tags when reporting using LightStep Java Tracer

### ISSUE THREAD

**Issue by iancs** [opentracing-contrib/java-specialagent#320]
Similar to other tracer options, please support a flag for defining global spans for the LightStep Java Tracer (see withTag).

@carlosalberto has raised his hand for this.

**Comment by safris** [comment]
Hi @iancs, this issue concerns the LightStep Tracer specifically. The [LightStep Tracer Plugin](https://github.com/lightstep/lightstep-tracer-java/tree/master/lightstep-tracer-jre-bundle) is responsible for consuming options that are specific for the LightStep Tracer, so this issue should be [filed with the LightStep Tracer Plugin](https://github.com/lightstep/lightstep-tracer-java/issues), respectively.

**Comment by safris** [comment]
Closing this issue as the more specific issue has been completed:
https://github.com/lightstep/lightstep-tracer-java/issues/220
