### ISSUE TITLE
Determine libs transitively supported by existing instrumentation

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#329]
Specify which 3rd-party libs are transitively supported, and specify it [here](https://github.com/opentracing-contrib/java-specialagent/#63-instrumented-libraries-by-existing-rules). In addition to the name of the transitively supported 3rd-party lib, also state which existing plugin/rule provides the transitive instrumentation.

**Comment by malafeev** [comment]
added twilio, ratpack, sparkjava
