### ISSUE TITLE
Static deferred attach is unavailable

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#356]
The `SpringWebMvcDeferredAttach` and `SpringBootDeferredAttach` plugins have dropped out of the bundled plugins list in SpecialAgent.

**Comment by pcasaes** [comment]
Would this be the cause of not detecting deferrers on Spring Boot applications?

```
.==============================================================.
|                    Static Deferred Attach                    |
|                    Enabled: true (default)                   |
|==============================================================|
|               To disable Static Deferred Attach,             |
|                 specify -Dsa.init.defer=false                |
|=============================================================='
 ' 0 deferrers were detected, overriding to: -Dsa.init.defer=false
```

**Comment by safris** [comment]
Hi @pcasaes, yes, this is correct. Static Deferred Attach is in fact not bundled in the SpecialAgent's main JAR artifact. In lieu of of this realization, I will remedy this issue, and will push the SpecialAgent [v1.5.6](https://github.com/opentracing-contrib/java-specialagent/milestone/3) release today (a week earlier than scheduled).
