### ISSUE TITLE
Manage mimepull dependency

### ISSUE THREAD

**Issue by ehmke** [opentracing-contrib/java-specialagent#361]
Spring-Boot depends on a outdated and missing version of mimepull: https://github.com/spring-projects/spring-boot/issues/14924
Using an empty local repository and a fresh checkout this will cause a dependency resolution error.

**Comment by safris** [comment]
Hi @ehmke, can you please elaborate on how this issue with Spring Boot relates to SpecialAgent?

**Comment by ehmke** [comment]
Also during build of SpecialAgent maven tries to resolve all dependencies including mimepull which was removed from maven-central.

**Comment by safris** [comment]
Hi @ehmke, can you please provide more clarity on this?

> Spring-Boot depends on a outdated and missing version of mimepull: spring-projects/spring-boot#14924
> Using an empty local repository and a fresh checkout this will cause a dependency resolution error.

Why does that matter for SpecialAgent?

> Also during build of SpecialAgent maven tries to resolve all dependencies including mimepull which was removed from maven-central.

Can you please point me to the error?

**Comment by ehmke** [comment]
Well, below you find the build log output. 

mimepull is a transitive dependency coming from: io.opentracing.contrib.specialagent.rule:spring-boot --> com.sun.xml.messaging.saaj:saaj-impl --> org.jvnet.mimepull:mimepull
And version 1.9.8 was removed from central maven repository.

It is a test dependency anyways, but without it, the build fails. Maybe it can be even excluded to make it work. Funny, that your build job is still working, but maybe, it's because it has cached its artifacts somewhere.

I guess, if the jar in question is already on your local maven repository (under .m2/respository), you won't see this error.

```
[...]
[INFO] --------< io.opentracing.contrib.specialagent.rule:spring-boot >--------
[INFO] Building SpecialAgent Rule for Spring Boot 1.5.7-SNAPSHOT        [10/70]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.jvnet.mimepull:mimepull:jar:1.9.8 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Java SpecialAgent 1.5.7-SNAPSHOT:
[INFO]
[INFO] Java SpecialAgent .................................. SUCCESS [  0.674 s]
[INFO] Utilities for SpecialAgent ......................... SUCCESS [  1.958 s]
[INFO] OpenTracing SpecialAgent API ....................... SUCCESS [  0.285 s]
[INFO] Fingerprint Utility for SpecialAgent ............... SUCCESS [  0.573 s]
[INFO] Assemble Maven Plugin for SpecialAgent ............. SUCCESS [  3.911 s]
[INFO] OpenTracing SpecialAgent ........................... SUCCESS [ 21.870 s]
[INFO] AgentRule Maven Plugin for SpecialAgent ............ SUCCESS [  2.652 s]
[INFO] ITest Maven Plugin for SpecialAgent ................ SUCCESS [  1.374 s]
[INFO] SpecialAgent Rules ................................. SUCCESS [  0.045 s]
[INFO] SpecialAgent Rule for Spring Boot .................. FAILURE [  0.637 s]
[INFO] SpecialAgent Rule for Spring Web MVC ............... SKIPPED
[...]
[INFO] SpecialAgent Rule for Apache Pulsar Client ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.694 s
[INFO] Finished at: 2020-01-20T12:18:38+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-boot: Could not resolve dependencies for project io.opentracing.contrib.specialagent.rule:spring-boot:jar:1.5.7-SNAPSHOT: Failure to find org.jvnet.mimepull:mimepull:jar:1.9.8 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
```

**Comment by ehmke** [comment]
Hi, this seemed to be strange issue in my local repository. After cleaning it up a little, everything was found, because it downloaded the missing dependency from another remote repository.
