### ISSUE TITLE
spring-boot deferred attach only works with flat-jar

### ISSUE THREAD

**Issue by ehmke** [opentracing-contrib/java-specialagent#362]
Currently spring-boot deferred attach only detects deferrers when a flat jar as created by the maven-shade-plugin is used.
Using the spring-boot-maven-plugin using repackage will create a hierarchical fat jar where special-agent fails to find any deferrers.

**Comment by safris** [comment]
Hi @ehmke, this has been fixed and pushed to Maven Central Snapshot repository. If you could, please [download the development build of SpecialAgent](https://github.com/opentracing-contrib/java-specialagent#2112-development), and confirm whether this issue is resolved.

**Comment by ehmke** [comment]
@safris seems to work. Thanks.

**Comment by safris** [comment]
Thanks for the confirmation @ehmke. Closing this issue now.
