### ISSUE TITLE
Instrumentation Tests failing with Static Deferred Attach

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#377]
The following integration tests are failing when Static Deferred Attach is turned on:
* ~Spring WebSocket~
* ~Spring Messaging~
* ~Spring Kafka~
* ~Spring WebFlux~
* ~Spring RabbitMQ~
* ~Spring JMS~
* ~Spring WebMVC 5.0.0 & 5.2.1~
* ~Zuul~

**Comment by safris** [comment]
To allow these tests to pass, I have disabled Static Deferred Attach in these tests.

**Comment by safris** [comment]
I think all of these started failing due to [this commit](https://github.com/opentracing-contrib/java-specialagent/commit/c43b59dacd8167579020a5db1b68214bd8be997f), which a fix for #367. Basically, issue #367 brought to my attention that Static Deferred Attach was not working properly for higher versions of Spring Boot. For the higher versions, the hook was being activated prematurely. This means that, before, all these tests were running with a faulty Static Deferred Attach algorithm. And now, Static Deferred Attach is fixed, but the tests are now failing. Like with the `servlet` rule, there may be something similar happening here.

**Comment by malafeev** [comment]
that's not similar to `servlet`
here `*AgentIntercept` is never called.
looks like spring rules never triggered.

**Comment by safris** [comment]
@malafeev, I've rewritten the Static Deferred Attach hooks for Spring Boot and Spring WebMVC. This has resulted in `spring-kafka` tests passing, so I've reactivated deferred attach for `spring-kafka`. The other lib tests are still failing.

**Comment by ehmke** [comment]
Hey @safris, I now run into some more trouble which only came obvious when I tried to look into the reported spans: turns out, and that is why I am posting it here, one of our service doesn't seem to report any spans when started deferred.
I didn't find out, what exactly is different to non-deferred mode. Anyways, it starts to initialize all the rules after the service came up and so on. It is not, that it would defer endlessly.

**Comment by malafeev** [comment]
**spring-webflux:**
method `org.springframework.web.server.handler.DefaultWebFilterChain.initChain(...)` is called for both cases: enabled and disabled static deferred attach.
- For disabled static deferred attach this method is intercepted by `io.opentracing.contrib.specialagent.rule.spring.webflux.filters.SpringWebFluxAgentIntercept.filters(...)`
- For enabled static deferred attach this method is not intercepted, although called
