### ISSUE TITLE
No dependencies.tfg registered for rule 

### ISSUE THREAD

**Issue by deepakgoenka** [opentracing-contrib/java-specialagent#38]
Hi,

I am trying to add a new rule to opentracing's special agent. let us call it opentracing-specialagent-is.
I have created a new class which implements AgentRule and prepared the opentracing-specialagent-1.0.1.jar and i have verified that my rule plugin is present inside META-INF/opentracing-specialagent.

My AgentRule class is very simple where i am trying to intercept entry to one of my method com.is.HTTPDispatch.handleRequest()  and inside the onEnter method i start a span and close the span in onExit method. I am not doing anything with the intercerpted class, not even having a reference to that in Advice.onEnter/onExit methods.

But when i start my java application with this agent then i get this error while it tries to transform my class.

INFO   | jvm 1    | 2019/04/04 11:54:05 | java.lang.IllegalStateException: No dependencies.tgf was registered for: file:/C:/workspace/temp/opentracing-specialagent1773856304519991467/META-INF/opentracing-specialagent/opentracing-specialagent-is-1.0.1.jar
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at io.opentracing.contrib.specialagent.SpecialAgent.linkRule(SpecialAgent.java:489)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at io.opentracing.contrib.specialagent.ByteBuddyManager$TransformationListener.onTransformation(ByteBuddyManager.java:162)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Listener$Compound.onTransformation(AgentBuilder.java:1796)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10136)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10551)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10514)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10889)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10836)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.lang.ClassLoader.defineClass1(Native Method)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.security.AccessController.doPrivileged(Native Method)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO   | jvm 1    | 2019/04/04 11:54:05 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Can someone help me to resolve this

**Comment by SevaSafris** [comment]
Have you followed all of the requirements in the opentracing-specialagent-api? Specifically [this one](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-specialagent-api#packaging), which involves agentrule-maven-plugin.

**Comment by deepakgoenka** [comment]
Thanks, i had commented the fingerprint and tree sections in pom and uncommenting them generates the fingerprint and dependencies.tfg files.

However i have other class loading issues in my application (while using the open tracing agent) which i am looking into now.
