### ISSUE TITLE
Readme link to last stable release is incorrect

### ISSUE THREAD

**Issue by LSwiatek** [opentracing-contrib/java-specialagent#386]
https://github.com/opentracing-contrib/java-specialagent#2111-stable

both hyperlink and wget command should be updated to

`wget -O opentracing-specialagent-1.5.6.jar "https://repo1.maven.org/maven2/io/opentracing/contrib/specialagent/opentracing-specialagent/1.5.6/opentracing-specialagent-1.5.6.jar"
`

**Comment by safris** [comment]
Hi @LSwiatek, thank you kindly for the note! I've fixed this in the README.md.
