### ISSUE TITLE
`ThreadAgentIntercept` should not close Scope

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#392]
[This code](https://github.com/opentracing-contrib/java-specialagent/blob/c9dbbcb6fc5aafda14443c37aabf4ac2ba5241c0/rule/thread/src/main/java/io/opentracing/contrib/specialagent/rule/thread/ThreadAgentIntercept.java#L63-L64) should not exist, because of [this](https://javadoc.io/doc/io.opentracing/opentracing-api/latest/io/opentracing/Tracer.html#activateSpan-io.opentracing.Span-):
> It is a programming error to neglect to call Scope.close() on the returned instance, and it may lead to memory leaks as the Scope may remain in the thread-local stack.

It is the responsibility of the tracing instrumentation code to close scopes. Having `ThreadAgentIntercept` automatically close scopes results in functional coupling. With this coupling, it is possible that certain instrumentations have been created to rely on this coupling (which is an error, as the javadoc specifies). If, for some reason, the `thread` plugin is chosen to be disabled, then scopes will not automatically be closed, and the instrumentations will therefore have different behavior.

**Comment by malafeev** [comment]
scope is created by `ThreadAgentItercept`: https://github.com/opentracing-contrib/java-specialagent/blob/master/rule/thread/src/main/java/io/opentracing/contrib/specialagent/rule/thread/ThreadAgentIntercept.java#L54
And it is put to thread local map of ThreadAgentItercept.

Then this scope is closed by ThreadAgentItercept (it is retrieved from thread local map of ThreadAgentItercept).

If thread plugin is disabled then scope is not created so nothing to close and no memory leak.

**Comment by safris** [comment]
Yes, I can see this now. So the follow-up question is: does the `ThreadAgentItercept` need to create a new scope for the new thread? Can it not use the scope of the parent thread?

**Comment by malafeev** [comment]
For each new thread we need to create a new scope from parent thread span,
and close scope when thread is finished.
https://github.com/opentracing/opentracing-java#deferring-asynchronous-work

**Comment by safris** [comment]
Thanks for the info @malafeev. After beating my head against the wall trying to figure this out, it seems the API's architecture would not allow us to take advantage of [`InheritableThreadLocal`](https://docs.oracle.com/javase/7/docs/api/java/lang/InheritableThreadLocal.html) after all. Closing this issue.
