### ISSUE TITLE
support for Jetty 9.4?

### ISSUE THREAD

**Issue by randallt** [opentracing-contrib/java-specialagent#394]
You seem to support Spring 5, but not Jetty 9.4. From what I can tell, Spring 5 requires Jetty 9.4. Can you clarify?

**Comment by safris** [comment]
Hi @randallt, [here](https://github.com/opentracing-contrib/java-specialagent/tree/master/test/servlet-jetty) are the versions of Jetty we support:

**Comment by safris** [comment]
Hi @randallt, is there an actionable deliverable for this issue? If yes, please let me know. Otherwise, I'd like to remove issues from our backlog as there are currently many.

**Comment by randallt** [comment]
No, you are correct. Closing.
