### ISSUE TITLE
Mule integration does not work with jdk11

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#405]

**Comment by jam01** [comment]
So this works locally for me and also worked on Github's CI. So it seems to be something related to Travis' JDK version.

**Comment by safris** [comment]
Do you wanna create a PR where you activate jdk11? We can work on it together.

**Comment by jam01** [comment]
I'll open one, yeah

**Comment by safris** [comment]
Hi @jam01, I've had to [turn off integration tests for Mule](https://github.com/opentracing-contrib/java-specialagent/blob/master/.travis.yml#L351-L360), because the tests started failing in jdk8 too for some reason.
