### ISSUE TITLE
Not showing up data in lightstep

### ISSUE THREAD

**Issue by arpit728** [opentracing-contrib/java-specialagent#409]
Command I used to launch my application.

```
java -javaagent:$(SPECIALAGENT_JAR) \
	-Dsa.tracer=lightstep \
	-Dsa.log.level=$(LOGLEVEL) \
	-Dsa.config=ls_tracer.properties \
	-Dsa.instrumentation.plugins.verbose=true \
	-Dls.componentName=$(SERVICE_NAME) \
	-Dls.collectorHost="lightstep-setup.staging.sharechat.internal" \
	-Dls.collectorProtocol="http" \
	-Dls.collectorPort="80" \
	-jar $(full_path_to_your_jar_file)
```

Sample app I created for demo can be found [here](https://github.com/arpit728/opentracing-demo).

Special agent version I used [opentracing-specialagent-1.5.7.jar](https://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST)

ls_tracer.properties 
```
ls.accessToken=XXXXX
```

**Comment by safris** [comment]
Hi @arpit728, thank you for posting this issue, and apologies for the delay. You have stumbled on issue #382 regarding Static Deferred Attach not triggering correctly for Spring Boot applications. You have a couple of options to resolve this:
1. You can turn off Static Deferred Attach: `-Dsa.init.defer=false`. The drawback of this will be a lengthier startup time.
1. You can use [the development build](https://github.com/opentracing-contrib/java-specialagent#2112-development), in which this issue has been fixed.
1. You can wait until v1.5.8 is released, which is scheduled for tomorrow (2020-2-14).

**Comment by safris** [comment]
Hi @arpit728, I am closing this as we are about to release v1.5.9.
