### ISSUE TITLE
Spring Boot Application taking too long to start | Spcial Agent | Lightstep Tracer

### ISSUE THREAD

**Issue by arpit728** [opentracing-contrib/java-specialagent#421]
I am using version ```1.5.6``` of special-agent.

The startup time of my spring boot application is around ```10 Sec.``` when I statically attach the agent  the startup time of the application goes up to ```3-5``` minutes. When attaching the agent dynamically, no data shows up.

**Command I used to launch the application**
```
java -jar application.jar
```
**Command I used to launch the app with static attach**
```
java -javaagent:$SPECIAL_AGENT_JAR \
        -Dsa.tracer=lightstep \
        -Dsa.log.level=INFO \
        -Dls.accessToken=$LS_TOKEN \
        -Dsa.tracer.plugins.enable=false \
        -Dls.componentName="test-app-15" \
        -Dls.collectorHost="lightstep-host" \
        -Dls.collectorProtocol="http" \
        -Dls.collectorPort="80" \
        -jar application.jar
```
**Command I used to attach the agent dynamically**
```
java -Dsa.tracer=lightstep \
	-Dsa.log.level=INFO \
	-Dsa.instrumentation.plugins.verbose=true \
	-Dls.componentName=api-gateway \
	-Dls.collectorHost="lightstep-host" \
	-Dls.collectorProtocol="http" \
        -Dls.accessToken=$LIGHTSTEP_TOKEN \
	-Dls.collectorPort="80" \
	-Xbootclasspath/a:$JAVA_HOME/lib/tools.jar \
	-jar $SPECIAL_AGENT_JAR PID
```

Sample app I created for demo can be found [here](https://github.com/arpit728/opentracing-demo).

**Comment by safris** [comment]
Hi @arpit728, can you test with v1.5.8 and let me know the results?

**Comment by arpit728** [comment]
@safris Thanks, it's working.

**Comment by safris** [comment]
Hi @arpit728, the prior versions had a number of outstanding issues regarding Static Deferred Attach. You can review the [release notes](https://github.com/opentracing-contrib/java-specialagent/releases) for details.

**Comment by arpit728** [comment]
@safris 
Thanks for sharing.

**Comment by safris** [comment]
Hi @arpit728, I'll close this issue. If you experience any other problems, don't hesitate to open another issue.
