### ISSUE TITLE
Using underlying Tracer with GRPC and protobuf

### ISSUE THREAD

**Issue by arpit728** [opentracing-contrib/java-specialagent#430]
I am using lightstep as the underlying tracer, lightstep supports  protocol buffers over GRPC,

I couldn't find a way to use lightstep with grpc, I think it's not configurable from special agent.

**Comment by malafeev** [comment]
grpc is not supported by https://github.com/lightstep/lightstep-tracer-java/tree/master/lightstep-tracer-jre-bundle

**Comment by arpit728** [comment]
@malafeev It does support but not by default, you can add dependencies of `tracer-grpc` and it works.
To make it work with the specialagent, I added those dependencies and created jar of `lightstep-tracer-jre-bundle` post that I supplied path of that jar in `sa.tracer` parameter.

**Comment by malafeev** [comment]
If bundle contains `tracer-okhttp`  then tracer uses OkHttp, if bundle contains `tracer-grpc` then tracer uses gRPC.
because SpecialAgent cannot contain both choice is to use OkHttp (default).
for gRPC you need custom tracer as you built.
not sure that we can fix it somehow here.

**Comment by safris** [comment]
@arpit728, the LightStep Tracer Plugin is decoupled from SpecialAgent, which means its internals are outside the scope of SpecialAgent. If you want the LightStep Tracer Plugin to support gRPC as the transport protocol via activation with a property, then such a request can only be fulfilled by the [LightStep Tracer Plugin project itself](https://github.com/lightstep/lightstep-tracer-java/tree/master/lightstep-tracer-jre-bundle).
