### ISSUE TITLE
Jaeger sees no traces from the demo project Microdonuts 

### ISSUE THREAD

**Issue by anhtuanluu36** [opentracing-contrib/java-specialagent#431]
I following the instruction with special agent 1.5.8 but I do not see anything on Jaeger
https://github.com/opentracing-contrib/java-specialagent-demo

I saw the same issue on java-specialagent-demo but no one answer it.
https://github.com/opentracing-contrib/java-specialagent-demo/issues/11

Please support us.

**Comment by malafeev** [comment]
I added comments to opentracing-contrib/java-specialagent-demo#11

**Comment by anhtuanluu36** [comment]
Thank you! I saw it.
