### ISSUE TITLE
Implement optional deferrable = false for rule

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-specialagent#445]
For example:
next line should be executed  regardless enabled/disabled static deferred attach

https://github.com/opentracing-contrib/java-specialagent/blob/master/rule/spring-webflux/src/main/java/io/opentracing/contrib/specialagent/rule/spring/webflux/SpringWebFluxChainAgentRule.java#L58

**Comment by safris** [comment]
Hi @malafeev, I implemented the "non-deferrable" construct [here](https://github.com/opentracing-contrib/java-specialagent/pull/new/non-deferrable). It seems, however, that this has not fixed the tests.
