### ISSUE TITLE
What's the purpose of SpecialAgentUtil.assertJavaAgentJarName() ?

### ISSUE THREAD

**Issue by william-tran** [opentracing-contrib/java-specialagent#456]
To make the integration of the agent jar as simple as possible for many services and teams, I'm trying to limit the number of places I need to specify the exact version of it. Container image assembly, where the agent jar is included in the image, and `java` options are specified in different places in our build+deploy infrastructure. `SpecialAgentUtil.assertJavaAgentJarName()` asserts the version being part of the file name, which forces coupling between image assembly and java options. What's the purpose of that check? Could that be turned off with a flag in the future?

**Comment by william-tran** [comment]
To answer my own question: I think this is to ensure the `Boot-Class-Path:` is setup properly; if the actual filename is different then the bootstrap classloader won't be used correctly. To solve my problem, I'm going to rewrite that one entry in the manifest and repackage it.

**Comment by safris** [comment]
Hi @william-tran, sorry for the delayed response. You are correct.
