### ISSUE TITLE
Determine min & max instrumented versions of libs supported by default

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#468]
- [x] Hystrix
- [x] JDBI
- [x] Ratpack
- [x] Solr Client
- [x] SparkJava
- [x] Spring Data
- [x] Spring Cloud
- [x] Twilio

For each, provide the following:
1. What is the instrumentation rule that supports this library?
1. Using `<passCompatibility>` tag in the relevant pom, add a clause to run compatibility test for the library's span of supported versions. (Use the `;` character to delimit _groupId:artifactId:[versionRange]_ specs). (This functionality is dependent on #469). ([See here](https://github.com/opentracing-contrib/java-specialagent/blob/master/rule/akka-http/pom.xml#L33) for example usage).
1. Implement test to show min supported version.

**Comment by malafeev** [comment]
JDBI uses JDBC. Do we need compatibility tests for JDBI? It will always pass for any version because JDBC is part of JDK.

**Comment by safris** [comment]
@malafeev, we need at least one integration test for each 3rd-party library we declare as "supported". We also need `<passCompatibility>` specs for each such 3rd-party library, except for the ones that instrument part of Java's APIs (JDBC and Concurrent).
