### ISSUE TITLE
Invalid gen classes in `thrift` rule

### ISSUE THREAD

**Issue by safris** [opentracing-contrib/java-specialagent#488]
It looks like the classes in the `gen` subpackage refer to the annotation class `@org.apache.thrift.annotation.Nullable` which is not provided in `org.apache.thrift:libthrift:0.10.0`. Were these classes generated by a more recent version?

The reason this bug was hidden from view is because the lightstep tracer bundle jar packages a newer version of the Thrift libraries.

**Comment by malafeev** [comment]
yes, it was generated by 0.12.0.
I will regenerate by 0.10.0 and replace them.

**Comment by malafeev** [comment]
how about integration tests? We have tests for 0.10.0 and 0.12.0
If I will replace 0.10.0 then tests of 0.12.0 will use 0.10.0 classes
so I should put 0.12.0 classes in 0.12.0 test?

**Comment by safris** [comment]
Will the 0.10.0 classes work with 0.12.0? If yes, then we should be fine.

**Comment by malafeev** [comment]
yes they will work
