### ISSUE TITLE
Kafka Streams Processor support

### ISSUE THREAD

**Issue by william-tran** [opentracing-contrib/java-specialagent#490]
I'm migrating tracing auto-instrumentation from Datadog's dd-java-agent to this project. I found traces are not propagating though a stream processor topology like they were before, and it's possible that there are some missing rules specifically around the Kafka Streams Processor api. Here's what the DD agent does:  https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java

Would it make sense to port this over?

**Comment by safris** [comment]
Hi @william-tran, thanks for this issue. We'll take a look!
