### ISSUE TITLE
Is custom Integration rules not supported any more?

### ISSUE THREAD

**Issue by jianshaow** [opentracing-contrib/java-specialagent#528]
I found that specialagent libraries, except "opentracing-specialagent“ the total package, cannot be fetched from public maven repository since 1.6.1, is it on purpose? or just temporary status?

Actually, I developed some custom rules based on 1.5.8, now they cannot be upgraded to latest version without the libraries.

**Comment by safris** [comment]
Hi @jianshaow, thank you for this note! This was actually on purpose, but you bring up a good point regarding custom rules. The original intention was to encourage people to pull the `java-specialagent` project, and to build it themselves to get the latest `opentracing-specialagent-api`. However, your use-case is absolutely valid. I have updated the POM to release `opentracing-specialagent-util` and `opentracing-specialagent-api` like in v1.6.1.
