### ISSUE TITLE
About Intercept org.apache.http.nio.client.HttpAsyncClient

### ISSUE THREAD

**Issue by code98** [opentracing-contrib/java-specialagent#535]
There is no Intercept org.apache.http.nio.client.HttpAsyncClient interface in the httpclient rule. Is it because of technical problems or forget this interception?

Thank you

--------------------------------------------------------------------
Follow up

org.apache.http.nio.client.HttpAsyncClient interception I have developed here, is being tested, if it passes, I submit

**Comment by safris** [comment]
Hi @code98, sorry for the late response to this issue. We put in a significant amount of work into v1.7.0, and simply did not have time to address all issues yet. If you could submit your intercept, I would greatly appreciate it!
