### ISSUE TITLE
reduce release time to less than 1 hr

### ISSUE THREAD

**Issue by andrewhsu** [opentracing-contrib/java-specialagent#538]
Talking with @safris about [releases](https://github.com/opentracing-contrib/java-specialagent/releases), currently seems like the release process may take over 10 hrs to complete and can easily eat a day or two of work. Desire is for the release process to take less than 1 hr in a reliable way.

**Comment by safris** [comment]
This is currently in the works [here](https://github.com/opentracing-contrib/java-specialagent/pull/536).

**Comment by safris** [comment]
Closing this, as we now have a fully successful build!
