### ISSUE TITLE
have PR checks complete in less than 1 hr, reliably

### ISSUE THREAD

**Issue by andrewhsu** [opentracing-contrib/java-specialagent#539]
Having a look at the [most recent 25 PRs merged to master](https://github.com/opentracing-contrib/java-specialagent/pulls?page=1&q=is%3Apr+is%3Amerged+closed%3A%3C2020-04-08), looks like only 9 of the PRs were green (36% merge on green).

Diving deeper into the green PRs that were merged, looks like travis tracks them as taking more than 24 hrs to complete, e.g.
* PR #515 travis [build 1724](https://travis-ci.org/github/opentracing-contrib/java-specialagent/builds/667633497)
* PR #507 travis [build 1684](https://travis-ci.org/github/opentracing-contrib/java-specialagent/builds/665882704)
* PR #506 travis [buid 1685](https://travis-ci.org/github/opentracing-contrib/java-specialagent/builds/666163614)

> Total time more than 24 hrs

I think setting the bar to have PR checks complete reliably in less than 1 hr would help with code changes to the repo and may possibly help with #538.

**Comment by safris** [comment]
Agreed! This is currently in the works [here](https://github.com/opentracing-contrib/java-specialagent/pull/536).

**Comment by safris** [comment]
Closing this, as we now have a fully successful build!
