### ISSUE TITLE
Get rid of spring-web-* rules 

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-specialagent#556]
Spring Web RestTemplate uses HttpUrlConnection to send requests.
But HttpUrlConnection is already instrumented.
Therefore Spring Web is redundant.

**Comment by code98** [comment]
![image](https://user-images.githubusercontent.com/10418235/83724361-bc11ff00-a672-11ea-8e63-0b154e77dacb.png)
![image](https://user-images.githubusercontent.com/10418235/83724430-d8ae3700-a672-11ea-8a9a-3ec64718af21.png)
![image](https://user-images.githubusercontent.com/10418235/83724495-f7143280-a672-11ea-8b8b-012505b57960.png)

RestTemplateBuilder.class line 594

I don't think the spring-web-3, spring-web-4, spring-web-5 components should be deleted, they should be kept.
If your project does not have okhttp and httpclient libraries, spring uses HttpURLConnection to send http requests by default, but during the startup process, spring will scan your project for better okhttp and httpclient libraries. HttpURLConnection.
At this time, you only enable HttpURLConnection interception will not take effect.
If this is recommended to the user, it will increase the use steps, for example:
1. Determine whether your project has okhttp and httpclient libraries
2. Choose to open the corresponding component.

If you retain the spring-web-3, spring-web-4, spring-web-5 components, users only need to determine what version of spring-web they have.
