### ISSUE TITLE
Release 1.7.4 version

### ISSUE THREAD

**Issue by malafeev** [opentracing-contrib/java-specialagent#584]

**Comment by malafeev** [comment]
1.7.4 released

**Comment by c3333** [comment]
@ Malafeev Malafeev hat dies selbst zugewiesen on 15 Jul
@ Malafeev Malafeev erwähnte dieses Problem on 15 Jul
Aktualisiert README bezüglich der neuesten Änderungen. Behebt auch # 578 # 583
 Zusammengeführt
malafeev hat ein Commit hinzugefügt, das auf dieses Problem verweist on 15 Jul
@ Malafeev
Release v1.7.4, re #584 …
733d01d
malafeev hat ein Commit hinzugefügt, das auf dieses Problem verweist on 15 Jul
@ Malafeev
Prepare v1.7.5-SNAPSHOT, re #584 …
