### ISSUE TITLE
Instruction to download the latest snapshot are not working

### ISSUE THREAD

**Issue by ledor473** [opentracing-contrib/java-specialagent#63]
As per the findings in #56, the README to download the latest SNAPSHOT of the Agent is incorrect.

Using the provided command you would get: `opentracing-specialagent-LATEST-SNAPSHOT.jar`
Or if you click on the link you would get something like: `opentracing-specialagent-1.1.1-20190430.153439-21.jar`
But it only work if you rename it to `opentracing-specialagent-1.1.1-SNAPSHOT.jar`

I wonder if the release would be affected the same way if you rename it to a custom name?

**Comment by kaushikdeb** [comment]
The MANIFEST.MF file in the generated jar file has this:
Boot-Class-Path: opentracing-specialagent-1.1.1-SNAPSHOT.jar

It does not reflect the LATEST-SNAPSHOT or the other version with date.

**Comment by SevaSafris** [comment]
@kaushikdeb, this is correct, and this is the reason for the error. The `Boot-Class-Path` property is set in the [pom.xml](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-specialagent/pom.xml#L418). I have corrected the installation instructions. Thank you both for helping with this issue.
