### ISSUE TITLE
jaeger-client-bundle not compatible with opentracing version

### ISSUE THREAD

**Issue by mtrejo** [opentracing-contrib/java-specialagent#64]
Using opentracing-specialagent-1.1.1, I started to see this error:
```
java.lang.AbstractMethodError: io.jaegertracing.internal.JaegerTracer.activateSpan(Lio/opentracing/Span;)Lio/opentracing/Scope;
```
After some investigation I found the jaeger-client version being used 0.33.1 is not compatible with opentracing-api version 0.32.0

**Comment by SevaSafris** [comment]
@mtrejo, the Jaeger Tracer has been updated in SpecialAgent to support OT API 0.32.0. Can you try your use-case with the latest 1.1.1-SNAPSHOT?

```bash
wget -O opentracing-specialagent-1.1.1-SNAPSHOT.jar "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST"
```

**Comment by ledor473** [comment]
@SevaSafris I've just tried with the latest published version and still see the issue.

I think the problem now is that there's no new version published, here's the output of the above command (look at the end of `Location:`) which seems to indicate the most recent build is from 2019-05-05 (3 days ago).
```
 $ wget -O opentracing-specialagent-1.1.2-SNAPSHOT.jar "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST"
--2019-05-08 10:34:07--  https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST

Resolving oss.sonatype.org (oss.sonatype.org)... 18.209.251.103, 34.203.177.218
Connecting to oss.sonatype.org (oss.sonatype.org)|18.209.251.103|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect

Location: https://oss.sonatype.org/service/local/repositories/snapshots/content/io/opentracing/contrib/specialagent/opentracing-specialagent/1.1.2-SNAPSHOT/opentracing-specialagent-1.1.2-20190505.052441-2.jar [following]
```

**Comment by SevaSafris** [comment]
@ledor473, the wget command you posted works correctly for me. Can you try again? Perhaps it was an intermittent issue.

**Comment by ledor473** [comment]
@SevaSafris it works now!
I was getting this file last time:
```
opentracing-specialagent-1.1.2-20190505.052441-2.jar
```
But now I see this which is more recent:
```
opentracing-specialagent-1.1.2-20190509.163504-5.jar
```

Also, I don't get a `AbstractMethodError` exception anymore 👍

**Comment by SevaSafris** [comment]
Great! I'm closing this issue. 👍
