### ISSUE TITLE
README Cleanup?

### ISSUE THREAD

**Issue by austinlparker** [opentracing-contrib/java-specialagent#69]
Would it be possible to re-organize the README? It's a bit sprawling. I'd think something like -

```
Table of Contents
Quick Start/How To Install
Configuration
--
Definitions
Objectives/Goals/Non-Goals
Plugins
Contribution Guidelines
```

This is just a suggestion to make it more friendly for first-time users. :)

**Comment by SevaSafris** [comment]
Great suggestion @austinlparker. I'll make this a priority for next week!

**Comment by SevaSafris** [comment]
@austinlparker, I've revised the README. Would love your feedback!

**Comment by austinlparker** [comment]
Looks fantastic, thanks!
