### ISSUE TITLE
DynamoDB Calls now fail with bad headers using LightStep

### ISSUE THREAD

**Issue by boostchicken** [opentracing-contrib/java-specialagent#86]
message: "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: InvalidSignatureException; Request ID: JLE25C7RCQKSIOBUF0IQP29EU3VV4KQNSO5AEMVJF66Q9ASUAAJG)"

**Comment by boostchicken** [comment]
#87

**Comment by malafeev** [comment]
#87 is not a bug

**Comment by boostchicken** [comment]
100% is a bug, not only is the span supporting the wrong the port, but it is also causing the headers to be miss signed to their abuse of them.

**Comment by malafeev** [comment]
Problem that in httpclient rule we modify request headers by injecting new span context.
But we should avoid that because request headers already contain injected span context.
It was injected by aws request handler. 
Looks like we break calculated checkum of the request.

**Comment by boostchicken** [comment]
You can add arbitrary headers in the v4 signature, just not like they are doing, and certainly not just assuming since a port isn't in the URI it's 80

**Comment by malafeev** [comment]
we don't modify port

**Comment by boostchicken** [comment]
If you spin that up right now and make a dynamodb call with that apache module on it will tell you it is over port 80 even though it is https. I bet you my bottom dollar.

https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html

Easy peasy to go ahead and sign whatever headers you want in v4

**Comment by malafeev** [comment]
span tag is incorrect for https. but it doesn't change the behavior of request. you can set any value.

**Comment by boostchicken** [comment]
Also, just go look at the code I highlighted.  It does not check schema one bit to determine if a port is not 80.  It just assumes if you don't have a port, it's 80.  That isn't the real crux of the problem, but it is extremely disheartening to see that I can't have httpclient and the aws-sdk instrumented?  It would be very easy to write some logic there to regenerate the canonical header after you edit and then re-sign it, either that or it should not be advertised that you support both.

**Comment by boostchicken** [comment]
Right, but your header injector does, which is why you have to regenerate a canonical request and re-sign it in the event that it is from the aws-sdk.

**Comment by malafeev** [comment]
this issue should be reopened.
Because if we fix #87 by setting 443 span tag for https it will not fix this problem.

**Comment by boostchicken** [comment]
Correct, but that issue needs to be fixed as well.

**Comment by SevaSafris** [comment]
Hi @boostchicken, did the fix to skip HttpClient instrumentation for AWS Client resolve this issue? If so, I'd like to close this issue.

**Comment by boostchicken** [comment]
Hey @SevaSafris yes it did.
