### ISSUE TITLE
Apache HttpClient Instrumention defaults to 80 more often than not

### ISSUE THREAD

**Issue by boostchicken** [opentracing-contrib/java-specialagent#87]
https://github.com/opentracing-contrib/java-specialagent/blob/003c538908342ed0af9a0dc256fc5f44b799bc8c/rules/specialagent-apache-httpclient/src/main/java/io/opentracing/contrib/specialagent/httpclient/HttpClientAgentIntercept.java#L56-L71

Almost unreal I have to write this, go look at how you are dealing with ports............  Let's just default everything to 80!

**Comment by malafeev** [comment]
we set span tag `Tags.PEER_PORT` to `uri.getPort() == -1 ? 80 : uri.getPort()`
what's wrong with that?

**Comment by boostchicken** [comment]
As stated in the other thread, even if the scheme is HTTPS the span will result in 80.

**Comment by malafeev** [comment]
OK, so issue that in case of https `Tags.PEER_PORT` should be set to `443`.
After bunch of comments now I see what you mean. Let's save time of each other next time by providing clear problem description.

**Comment by SevaSafris** [comment]
Hi @boostchicken, did the update to the Apache HttpClient Plugin resolve this issue re default ports? If so, I'd like to close this issue.
